import os

from google import genai

client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))


async def plugin(
    text: str, model: str = "gemini-2.0-flash", temperature: float | None = None
) -> str:
    res = await client.aio.models.generate_content(
        model=model,
        contents=text,
        config={"temperature": temperature},
    )
    if res.text is None:
        raise ValueError("No response was generated by the model.")
    return res.text
